description:  Read/update/delete entity representing a <<resourcePathName|!singularize>>
get:
  description: Get the collection item of <<resourcePathName|!singularize>>
  is: [ expandable: { expandableDoc: <<expandableDoc>> } ]
  responses:
    200:
      body:
        application/json:
          example: <<exampleReadItem>>
    204:
      body:
        application/json:
          example: !include ../samples/response-status/204.json
    400:
      body:
        application/json:
          example: !include ../samples/response-status/400.json
    401:
      body:
        application/json:
          example: !include ../samples/response-status/401.json
    403:
      body:
        application/json:
          example: !include ../samples/response-status/403.json
    404:
      body:
        application/json:
          example: !include ../samples/response-status/404.json
    405:
      body:
        application/json:
          example: !include ../samples/response-status/405.json
    409:
      body:
        application/json:
          example: !include ../samples/response-status/409.json
    410:
      body:
        application/json:
          example: !include ../samples/response-status/410.json
    500:
      body:
        application/json:
          example: !include ../samples/response-status/500.json
    503:
      body:
        application/json:
          example: !include ../samples/response-status/503.json
post:
  description: Update the collection item of <<resourcePathName|!singularize>>
  body:
    application/json:
      example: <<exampleUpdateItem>>
  responses:
    200:
      body:
        application/json:
          example: !include ../samples/response-status/200.json
    304:
      body:
        application/json:
          example: !include ../samples/response-status/304.json
    400:
      body:
        application/json:
          example: !include ../samples/response-status/400.json
    401:
      body:
        application/json:
          example: !include ../samples/response-status/401.json
    403:
      body:
        application/json:
          example: !include ../samples/response-status/403.json
    404:
      body:
        application/json:
          example: !include ../samples/response-status/404.json
    405:
      body:
        application/json:
          example: !include ../samples/response-status/405.json
    409:
      body:
        application/json:
          example: !include ../samples/response-status/409.json
    410:
      body:
        application/json:
          example: !include ../samples/response-status/410.json
    500:
      body:
        application/json:
          example: !include ../samples/response-status/500.json
    503:
      body:
        application/json:
          example: !include ../samples/response-status/503.json
delete:
  description: Delete the collection item of <<resourcePathName|!singularize>>
  responses:
    200:
      body:
        application/json:
          example: !include ../samples/response-status/200.json
    400:
      body:
        application/json:
          example: !include ../samples/response-status/400.json
    401:
      body:
        application/json:
          example: !include ../samples/response-status/401.json
    403:
      body:
        application/json:
          example: !include ../samples/response-status/403.json
    404:
      body:
        application/json:
          example: !include ../samples/response-status/404.json
    405:
      body:
        application/json:
          example: !include ../samples/response-status/405.json
    409:
      body:
        application/json:
          example: !include ../samples/response-status/409.json
    410:
      body:
        application/json:
          example: !include ../samples/response-status/410.json
    500:
      body:
        application/json:
          example: !include ../samples/response-status/500.json
    503:
      body:
        application/json:
          example: !include ../samples/response-status/503.json