description: OAuth 2.0 for authenticating all API requests.
type: OAuth 2.0
describedBy:
  headers:
    Authorization:
      description: |
        Used to send a valid OAuth 2 access token. Do not use
        with the "access_token" query string parameter.
      type: string
  queryParameters:
    access_token:
      description: |
        Used to send a valid OAuth 2 access token. Do not use together with
        the "Authorization" header
      type: string
  responses:
    400:
      description: Bad OAuth request.
      body:
        application/json:
          example: !include ../samples/response-status/400.json
    401:
      description: |
        Bad or expired token. This can happen if the user or Dropbox
        revoked or expired an access token. To fix, you should re-
        authenticate the user.
      body:
        application/json:
          example: !include ../samples/response-status/401.json
    403:
      description: |
        Bad OAuth request (wrong consumer key, bad nonce, expired
        timestamp...). Unfortunately, re-authenticating the user won't help here.
      body:
        application/json:
          example: !include ../samples/response-status/403.json
    404:
      description: OAuth resurce not found.
      body:
        application/json:
          example: !include ../samples/response-status/404.json
    405:
      description: Method of OAuth request is not allowed.
      body:
        application/json:
          example: !include ../samples/response-status/405.json
    409:
      description: Conflict in request.
      body:
        application/json:
          example: !include ../samples/response-status/409.json
    410:
      description: OAuth resource is not available.
      body:
        application/json:
          example: !include ../samples/response-status/410.json
    500:
      description: Internal server error.
      body:
        application/json:
          example: !include ../samples/response-status/500.json
    503:
      description: Service is unavailable.
      body:
        application/json:
          example: !include ../samples/response-status/503.json
settings:
  authorizationUri: https://idp.cpdn.sd2.cz/authorize
  accessTokenUri: https://idp.cpdn.sd2.cz/oauth/token
  authorizationGrants: [ code, token ]