description: Expandable feature for method that needs expand any element.
queryParameters:
  e:
    description: |
      The list of comma-separated properties used to expand field of the collection or the collection item.
      Use it only if you want expand any element from available expandable elements in current scope.
      General example: (calc,section.spec, ...)
    type: string
    required: false
    example: <<expandableDoc>>