description: Pagging feature for method that returns list of items.
queryParameters:
  offset:
    description: Offset items from start
    type: number
    example: 0
  limit:
    description: Items per page
    type: number
    example: 25