description: Pagging feature for method that returns list of items.
queryParameters:
  page:
    description: Page number
    type: number
    example: 1
  size:
    description: Page size
    type: number
    example: 10