description: Searchable feature for method that returns filtered collection.
queryParameters:
  q:
    description: |
      The list of semicolon-separated properties used to filter the collection.
      Use it only if you want filter the collection for selected parameters.
      General example: (color=blue;wheels=15; ...)
    type: string
    required: false
    example: <<searchableDoc>>