description: Searchable feature for method that returns filtered collection.
queryParameters:
  q:
    description: |
      The list of semicolon-separated properties used to filter the collection.
      Use it only if you want filter the collection for selected parameters.
      Some collections may have required parameters in filter query. These 
      parameters are with leading ! in example doc.
      General example: (color=blue;wheels=15; ...)
      Required param: (!color=blue)
    type: string
    required: false
    example: <<searchableDoc>>