description: Sortable feature for method that returns sorted collection.
queryParameters:
  s:
    description: |
      The list of comma-separated properties used to sort the results.
      By default, the column values are sorted in ascending order. 
      Can either be in the form of fieldName or fieldName:asc.
    type: string
    required: false
    example: <<sortableDoc>>