#%RAML 0.8
title: CPDN REST API
version: v1
baseUri: https://api.cpdn.sd2.cz/{version}
mediaType: application/json
protocols: [ HTTPS ]


resourceTypes:
  - readOnlyCollection:
      description: ReadOnly collection of <<resourcePathName>>.
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
  - collection:
      description: Collection of <<resourcePathName>>.
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
      post:
        description: | 
          Add a new <<resourcePathName|!singularize>>.
        body:
          application/json:
        responses:
          200:
            body:
              application/json:
                example: |
                  { "message": "The <<resourcePathName|!singularize>> has been properly entered" }
  - collection-item:
      description: Entity representing a <<resourcePathName|!singularize>>
      get:
        description: |
          Get the collection item of <<resourcePathName|!singularize>>
        responses:
          200:
            body:
              application/json:
                example: <<exampleItem>>
          404:
            body:
              application/json:
                example: !include samples/4xx.sample

/schemes:
  description: Scheme root resource
  get:
    description: List of Schemes
  /{scheme_id}:
    get:
      description: Get one entity of Scheme identified by SCHEME_ID
    /nodes:
    /sections:
    /requests:
    /mapPoints:
    /permissions:

/nodes:
  description: Node root resource
  type:
    collection:
      exampleCollection: !include samples/nodes.sample
  /{node_id}:
    type:
        collection-item:
          exampleItem: !include samples/node.sample
    /calc:
      type:
        collection-item:
          exampleItem: !include samples/node-calc.sample
    /mapPoint:
      type:
        collection-item:
          exampleItem: !include samples/node-mapPoint.sample
    /scheme:
      type:
        collection-item:
          exampleItem: !include samples/node-scheme.sample
    /spec:
      type:
        collection-item:
          exampleItem: !include samples/node-spec.sample

/sections:
  description: Section root resource
  get:
  /{section_id}:
    /calc:
    /nodes:
    /spec:

/mapPoints:
  description: MapPoint root resource
  get:
  /{mapPoint_id}:
    /node:
    /paths:
      /src:
      /dst:

/paths:
  description: Path root resource
  get:
  /{path_id}:
    /section: