#%RAML 0.8
title: CPDN REST API
version: v1
baseUri: https://api.cpdn.sd2.cz/{version}
mediaType: application/json
protocols: [ HTTPS ]
securedBy: [oauth_2_0]

securitySchemes:
  - oauth_2_0: !include schemes/oauth2.raml

resourceTypes:
  - collection: !include types/collection.raml
  - collection-item-read: !include types/collection-item-read.raml
  - collection-item-read-update: !include types/collection-item-read-update.raml
  - collection-item-read-update-delete: !include types/collection-item-read-update-delete.raml

traits:
  - paged: !include traits/paged.raml
  - searchable: !include traits/searchable.raml

/schemes:
  description: Scheme root resource
  /{scheme_id}:
    /nodes:
    /sections:
    /requests:
    /mapPoints:
    /permissions:
 
/nodes:
  description: Node root resource
  is: [ paged, searchable ]
  type:
    collection:
      exampleCollection: !include samples/read-body/nodes.json
      exampleCreateItem: !include samples/create-body/node.json
  /{node_id}:
    type:
        collection-item-read-update-delete:
          exampleReadItem: !include samples/read-body/node.json
          exampleUpdateItem: !include samples/update-body/node.json
    /calc:
      type:
        collection-item-read-update:
          exampleReadItem: !include samples/read-body/node-calc.json
          exampleUpdateItem: !include samples/update-body/node-calc.json
    /mapPoint:
      type:
        collection-item-read:
          exampleReadItem: !include samples/read-body/node-mapPoint.json
    /scheme:
      type:
        collection-item-read:
          exampleReadItem: !include samples/read-body/node-scheme.json
    /spec:
      type:
        collection-item-read-update:
          exampleReadItem: !include samples/read-body/node-spec.json
          exampleUpdateItem: !include samples/update-body/node-spec.json

/sections:
  description: Section root resource
  is: [ paged, searchable ]
  type:
    collection:
      exampleCollection: !include samples/read-body/sections.json
      exampleCreateItem: !include samples/create-body/section.json
  /{section_id}:
    type:
        collection-item-read-update-delete:
          exampleReadItem: !include samples/read-body/section.json
          exampleUpdateItem: !include samples/update-body/section.json
    /calc:
      type:
        collection-item-read-update:
          exampleReadItem: !include samples/read-body/section-calc.json
          exampleUpdateItem: !include samples/update-body/section-calc.json
    /nodes:
      type:
        collection-item-read:
          exampleReadItem: !include samples/read-body/section-paths.json
    /paths:
      type:
        collection-item-read:
          exampleReadItem: !include samples/read-body/section-paths.json
    /scheme:
      type:
        collection-item-read:
          exampleReadItem: !include samples/read-body/section-scheme.json
    /spec:
      type:
        collection-item-read-update:
          exampleReadItem: !include samples/read-body/section-spec.json
          exampleUpdateItem: !include samples/update-body/section-spec.json

/mapPoints:
  description: MapPoint root resource
  /{mapPoint_id}:
    /node:
    /paths:
      /src:
      /dst:
    /scheme:

/paths:
  description: Path root resource
  /{path_id}:
    /section:

/permissions:
  description: Schema permissions root resource